name: AutoCommitter

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script to update README
      run: python update_readme.py

    - name: Debug cron trigger time
      run: echo "This is a cron triggered run at $(date)"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "rmrichardson88"
        git config --global user.email "ryanmarkrichardson@gmail.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add README.md .counter
        git commit -m "Automated update via GitHub Actions" || echo "No changes to commit"
        git push
